# set defaults
DEF_CONFIG=""
DEF_NAME=proxy
DEF_FOREVER_LOGDIR=.
DEF_CHILD_LOGDIR=.
DEF_SCRIPTDIR=.

# load parameters
CONFIG=${1:-$DEF_CONFIG}
NAME=${2:-$DEF_NAME}
FOREVER_LOGDIR=${3:-$DEF_FOREVER_LOGDIR}
CHILD_LOGDIR=${4:-$DEF_CHILD_LOGDIR}
SCRIPTDIR=${5:-$DEF_SCRIPTDIR}

# start forever

forever start --uid $NAME --append -l $FOREVER_LOGDIR/$NAME.log --outFile $CHILD_LOGDIR/$NAME.out.log --errFile $CHILD_LOGDIR/$NAME.err.log $SCRIPTDIR/proxy.js $CONFIG
